
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label7;

	private global::Gtk.Label label6;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Entry nameBox;

	private global::Gtk.Entry phoneBox;

	private global::Gtk.Entry addressBox;

	private global::Gtk.Label label10;

	private global::Gtk.RadioButton singleBut;

	private global::Gtk.RadioButton widowBut;

	private global::Gtk.RadioButton marriedBut;

	private global::Gtk.Label label11;

	private global::Gtk.RadioButton collegeBut;

	private global::Gtk.RadioButton highschoolBut;

	private global::Gtk.RadioButton gradeBut;

	private global::Gtk.RadioButton noneBut;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Adı - Soyadı");
		this.fixed1.Add(this.label7);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
		w1.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Personelin");
		this.fixed1.Add(this.label6);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
		w2.X = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Telefonu");
		this.fixed1.Add(this.label8);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
		w3.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Adresi");
		this.fixed1.Add(this.label9);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label9]));
		w4.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nameBox = new global::Gtk.Entry();
		this.nameBox.CanFocus = true;
		this.nameBox.Name = "nameBox";
		this.nameBox.IsEditable = true;
		this.nameBox.InvisibleChar = '●';
		this.fixed1.Add(this.nameBox);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.nameBox]));
		w5.X = 100;
		w5.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.phoneBox = new global::Gtk.Entry();
		this.phoneBox.CanFocus = true;
		this.phoneBox.Name = "phoneBox";
		this.phoneBox.IsEditable = true;
		this.phoneBox.InvisibleChar = '●';
		this.fixed1.Add(this.phoneBox);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.phoneBox]));
		w6.X = 100;
		w6.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.addressBox = new global::Gtk.Entry();
		this.addressBox.HeightRequest = 250;
		this.addressBox.CanFocus = true;
		this.addressBox.Name = "addressBox";
		this.addressBox.IsEditable = true;
		this.addressBox.InvisibleChar = '●';
		this.fixed1.Add(this.addressBox);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.addressBox]));
		w7.X = 100;
		w7.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Medeni Hali");
		this.fixed1.Add(this.label10);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label10]));
		w8.X = 400;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.singleBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Bekar"));
		this.singleBut.CanFocus = true;
		this.singleBut.Name = "singleBut";
		this.singleBut.DrawIndicator = true;
		this.singleBut.UseUnderline = true;
		this.singleBut.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.singleBut);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.singleBut]));
		w9.X = 400;
		w9.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.widowBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Dul"));
		this.widowBut.CanFocus = true;
		this.widowBut.Name = "widowBut";
		this.widowBut.DrawIndicator = true;
		this.widowBut.UseUnderline = true;
		this.widowBut.Group = this.singleBut.Group;
		this.fixed1.Add(this.widowBut);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.widowBut]));
		w10.X = 400;
		w10.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.marriedBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Evli"));
		this.marriedBut.CanFocus = true;
		this.marriedBut.Name = "marriedBut";
		this.marriedBut.DrawIndicator = true;
		this.marriedBut.UseUnderline = true;
		this.marriedBut.Group = this.singleBut.Group;
		this.fixed1.Add(this.marriedBut);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.marriedBut]));
		w11.X = 400;
		w11.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Öğrenim Durumu");
		this.fixed1.Add(this.label11);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label11]));
		w12.X = 400;
		w12.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.collegeBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Üniversite"));
		this.collegeBut.CanFocus = true;
		this.collegeBut.Name = "collegeBut";
		this.collegeBut.DrawIndicator = true;
		this.collegeBut.UseUnderline = true;
		this.collegeBut.Group = this.singleBut.Group;
		this.fixed1.Add(this.collegeBut);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.collegeBut]));
		w13.X = 400;
		w13.Y = 275;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.highschoolBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Lise"));
		this.highschoolBut.CanFocus = true;
		this.highschoolBut.Name = "highschoolBut";
		this.highschoolBut.DrawIndicator = true;
		this.highschoolBut.UseUnderline = true;
		this.highschoolBut.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.highschoolBut);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.highschoolBut]));
		w14.X = 400;
		w14.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.gradeBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("İlköğretim"));
		this.gradeBut.CanFocus = true;
		this.gradeBut.Name = "gradeBut";
		this.gradeBut.DrawIndicator = true;
		this.gradeBut.UseUnderline = true;
		this.gradeBut.Group = this.highschoolBut.Group;
		this.fixed1.Add(this.gradeBut);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.gradeBut]));
		w15.X = 400;
		w15.Y = 225;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.noneBut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Yok"));
		this.noneBut.CanFocus = true;
		this.noneBut.Name = "noneBut";
		this.noneBut.DrawIndicator = true;
		this.noneBut.UseUnderline = true;
		this.noneBut.Group = this.singleBut.Group;
		this.fixed1.Add(this.noneBut);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.noneBut]));
		w16.X = 400;
		w16.Y = 300;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 975;
		this.DefaultHeight = 552;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
